import React, { useState, lazy, Suspense } from 'react';
import type { ReportRecord, Task, SchoolSettings, UserProfile } from '../types';
import Spinner from './common/Spinner';

const MoodOverTimeChart = lazy(() => import('./analytics/MoodOverTimeChart'));
const PerformanceTrendChart = lazy(() => import('./analytics/PerformanceTrendChart'));
const EngagementHeatmap = lazy(() => import('./analytics/EngagementHeatmap'));


interface AnalyticsViewProps {
    reports: ReportRecord[];
    tasks: Task[];
    schoolSettings: SchoolSettings | null;
    userProfile: UserProfile;
}

type AnalyticsTab = 'mood' | 'performance' | 'engagement';

const AnalyticsView: React.FC<AnalyticsViewProps> = ({ reports, tasks, schoolSettings, userProfile }) => {
    const [activeTab, setActiveTab] = useState<AnalyticsTab>('mood');

    const handlePrint = () => {
        window.print();
    };

    const TabButton: React.FC<{ label: string; tabId: AnalyticsTab }> = ({ label, tabId }) => (
        <button
            onClick={() => setActiveTab(tabId)}
            className={`px-4 py-2 text-sm font-semibold rounded-t-lg border-b-2 ${
                activeTab === tabId
                ? 'text-blue-600 border-blue-600'
                : 'text-slate-500 border-transparent hover:border-slate-300'
            }`}
        >
            {label}
        </button>
    );

    return (
        <div className="space-y-6 animate-fade-in">
            <div className="flex justify-between items-center no-print">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Analytics Dashboard</h1>
                    <p className="text-slate-600 dark:text-slate-300 mt-1">Visualize trends and performance across the school.</p>
                </div>
                <button
                    onClick={handlePrint}
                    className="px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700"
                >
                    Export Page to PDF
                </button>
            </div>

            <div className="printable-area rounded-2xl border border-slate-200/60 bg-white/60 p-6 backdrop-blur-xl shadow-xl dark:border-slate-800/60 dark:bg-slate-900/40">
                <div className="print:block hidden mb-4">
                    <h1 className="text-2xl font-bold">{schoolSettings?.name || 'School Analytics Report'}</h1>
                    <p className="text-sm">Generated by: {userProfile.name} on {new Date().toLocaleDateString()}</p>
                </div>
                <div className="border-b border-slate-200/60 dark:border-slate-700/60 no-print">
                    <TabButton label="Mood Over Time" tabId="mood" />
                    <TabButton label="Performance Trends" tabId="performance" />
                    <TabButton label="Engagement Heatmap" tabId="engagement" />
                </div>
                <div className="mt-6">
                    <Suspense fallback={<div className="flex justify-center items-center h-64"><Spinner size="lg" /></div>}>
                        {activeTab === 'mood' && <MoodOverTimeChart reports={reports} />}
                        {activeTab === 'performance' && <PerformanceTrendChart tasks={tasks} />}
                        {activeTab === 'engagement' && <EngagementHeatmap reports={reports} />}
                    </Suspense>
                </div>
            </div>
        </div>
    );
};

export default AnalyticsView;
