
import React, { useState, useEffect, useMemo } from 'react';
import type { RoleDetails, RoleTitle, UserProfile } from '../types';
import { ALL_PERMISSIONS } from '../constants';
import Spinner from './common/Spinner';
import AssignRoleModal from './AssignRoleModal';
import { UsersIcon, ChevronDownIcon } from './common/icons';

// Role Form Modal (for creating and editing)
const RoleFormModal: React.FC<{
    role: RoleDetails | null;
    allRoles: RoleDetails[];
    onClose: () => void;
    onSave: (roleData: RoleDetails) => Promise<void>;
}> = ({ role, allRoles, onClose, onSave }) => {
    const [title, setTitle] = useState<RoleTitle>((role?.title || '') as RoleTitle);
    const [description, setDescription] = useState(role?.description || '');
    const [permissions, setPermissions] = useState<string[]>(role?.permissions || []);
    const [reportingQuotaDays, setReportingQuotaDays] = useState(role?.reportingQuotaDays || '');
    const [reportingQuotaCount, setReportingQuotaCount] = useState(role?.reportingQuotaCount || '');
    const [isSaving, setIsSaving] = useState(false);
    const isEditing = !!role;

    const handlePermissionChange = (permission: string, isChecked: boolean) => {
        if (isChecked) {
            setPermissions(prev => [...prev, permission]);
        } else {
            setPermissions(prev => prev.filter(p => p !== permission));
        }
    };

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!title.trim() || !description.trim()) {
            alert('Title and description are required.');
            return;
        }
        if (!isEditing && allRoles.some(r => r.title.toLowerCase() === title.toLowerCase().trim())) {
            alert('A role with this title already exists.');
            return;
        }

        setIsSaving(true);
        // FIX: Add placeholder id and school_id to satisfy the RoleDetails type.
        // The actual school_id is set in the parent handler, and id is generated by DB for new roles.
        const roleData: RoleDetails = {
            id: role?.id ?? 0,
            school_id: role?.school_id ?? 0,
            title: title.trim() as RoleTitle,
            description: description.trim(),
            permissions,
            reportingQuotaDays: reportingQuotaDays ? Number(reportingQuotaDays) : undefined,
            reportingQuotaCount: reportingQuotaCount ? Number(reportingQuotaCount) : undefined,
            aiAnalysisFocus: role?.aiAnalysisFocus || '',
            aiRoutingInstructions: role?.aiRoutingInstructions || ''
        };
        await onSave(roleData);
        setIsSaving(false);
        onClose();
    };

    return (
         <div className="fixed inset-0 bg-black/30 backdrop-blur-sm flex justify-center items-center z-50 animate-fade-in">
            <div className="rounded-2xl border border-slate-200/60 bg-white/80 p-6 backdrop-blur-xl shadow-2xl dark:border-slate-800/60 dark:bg-slate-900/80 w-full max-w-2xl m-4 flex flex-col max-h-[90vh]">
                <form onSubmit={handleSave} className="flex flex-col h-full">
                    <h2 className="text-xl font-bold text-slate-800 dark:text-white">{isEditing ? `Edit Role: ${role.title}` : 'Create New Role'}</h2>
                    <div className="space-y-4 my-4">
                         <div>
                            <label htmlFor="role-title" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Role Title</label>
                            <input
                                type="text"
                                id="role-title"
                                value={title}
                                onChange={e => setTitle(e.target.value as RoleTitle)}
                                disabled={isEditing}
                                className="mt-1 block w-full rounded-xl border border-slate-300 bg-white/80 dark:border-slate-700 dark:bg-slate-800/80 p-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm disabled:bg-slate-200/50 dark:disabled:bg-slate-700/50"
                                required
                            />
                        </div>
                        <div>
                            <label htmlFor="role-description" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Description</label>
                            <textarea
                                id="role-description"
                                value={description}
                                onChange={e => setDescription(e.target.value)}
                                rows={2}
                                className="mt-1 block w-full rounded-xl border border-slate-300 bg-white/80 dark:border-slate-700 dark:bg-slate-800/80 p-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm"
                                required
                            ></textarea>
                        </div>
                         <div>
                            <h3 className="text-lg font-semibold text-slate-800 dark:text-white">Reporting Quota (Optional)</h3>
                            <div className="grid grid-cols-2 gap-4 mt-2">
                                <div>
                                    <label htmlFor="quota-count" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Reports Required</label>
                                    <input type="number" id="quota-count" value={reportingQuotaCount} onChange={e => setReportingQuotaCount(e.target.value)} className="mt-1 block w-full rounded-xl border border-slate-300 bg-white/80 dark:border-slate-700 dark:bg-slate-800/80 p-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" placeholder="e.g., 5" />
                                </div>
                                <div>
                                    <label htmlFor="quota-days" className="block text-sm font-medium text-slate-700 dark:text-slate-300">Per # of Days</label>
                                    <input type="number" id="quota-days" value={reportingQuotaDays} onChange={e => setReportingQuotaDays(e.target.value)} className="mt-1 block w-full rounded-xl border border-slate-300 bg-white/80 dark:border-slate-700 dark:bg-slate-800/80 p-2 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" placeholder="e.g., 7" />
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <h3 className="text-lg font-semibold text-slate-800 dark:text-white">Permissions</h3>
                    <div className="flex-grow overflow-y-auto mt-2 border border-slate-200/80 dark:border-slate-700/80 rounded-lg p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-4 gap-y-2">
                        {ALL_PERMISSIONS.map(permission => (
                             <label key={permission} className="flex items-center space-x-2">
                                <input
                                    type="checkbox"
                                    checked={permissions.includes(permission)}
                                    onChange={e => handlePermissionChange(permission, e.target.checked)}
                                    className="h-4 w-4 rounded border-slate-300 dark:border-slate-600 text-blue-600 focus:ring-blue-500 bg-transparent"
                                />
                                <span className="text-sm text-slate-700 dark:text-slate-300">{permission}</span>
                            </label>
                        ))}
                    </div>

                    <div className="flex justify-end space-x-3 pt-4">
                        <button type="button" onClick={onClose} className="px-4 py-2 bg-slate-500/20 text-slate-800 dark:text-white font-semibold rounded-lg hover:bg-slate-500/30">Cancel</button>
                        <button type="submit" disabled={isSaving} className="px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 disabled:bg-blue-400 flex items-center">
                            {isSaving && <Spinner size="sm" />}
                            <span className={isSaving ? 'ml-2' : ''}>Save Role</span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    )
}

// Main Role Manager View
interface RoleManagerProps {
    roles: RoleDetails[];
    onSaveRole: (roleData: RoleDetails) => Promise<void>;
    users: UserProfile[];
    userRoleAssignments: { user_id: string; role_id: number }[];
    onUpdateRoleAssignments: (roleId: number, userIds: string[]) => Promise<void>;
}

const RoleManager: React.FC<RoleManagerProps> = ({ roles = [], onSaveRole, users = [], userRoleAssignments = [], onUpdateRoleAssignments }) => {
    const [editingRole, setEditingRole] = useState<RoleDetails | null>(null);
    const [assigningRole, setAssigningRole] = useState<RoleDetails | null>(null);
    const [isFormModalOpen, setIsFormModalOpen] = useState(false);
    const [isAssignModalOpen, setIsAssignModalOpen] = useState(false);
    const [expandedUsersRole, setExpandedUsersRole] = useState<number | null>(null);

    const handleEdit = (role: RoleDetails) => {
        setEditingRole(role);
        setIsFormModalOpen(true);
    };

    const handleCreate = () => {
        setEditingRole(null);
        setIsFormModalOpen(true);
    };
    
    const handleAssign = (role: RoleDetails) => {
        setAssigningRole(role);
        setIsAssignModalOpen(true);
    };

    const handleCloseModal = () => {
        setIsFormModalOpen(false);
        setEditingRole(null);
    };
    
    const handleCloseAssignModal = () => {
        setIsAssignModalOpen(false);
        setAssigningRole(null);
    };
    
    const toggleExpandedUsers = (roleId: number) => {
        setExpandedUsersRole(prev => prev === roleId ? null : roleId);
    }

    return (
        <div className="space-y-6 animate-fade-in">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Role Management</h1>
                    <p className="text-slate-600 dark:text-slate-300 mt-1">Define custom roles and manage their permissions.</p>
                </div>
                <button onClick={handleCreate} className="px-4 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700">Create New Role</button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {roles.map(role => {
                    const assignedUserIds = userRoleAssignments.filter(a => a.role_id === role.id).map(a => a.user_id);
                    const assignedUsers = users.filter(u => assignedUserIds.includes(u.id));
                    const permissions = role.permissions || []; // SAFE ACCESS
                    
                    return (
                    <div key={role.title} className="rounded-2xl border border-slate-200/60 bg-white/60 p-4 backdrop-blur-xl shadow-xl dark:border-slate-800/60 dark:bg-slate-900/40 flex flex-col card-hover">
                        <div className="flex-grow">
                            <h3 className="text-lg font-bold text-slate-800 dark:text-white">{role.title}</h3>
                            <p className="text-sm text-slate-600 dark:text-slate-300 mt-1">{role.description}</p>
                            
                            <div className="mt-4 flex items-center justify-between bg-slate-100 dark:bg-slate-800/50 p-2 rounded-lg cursor-pointer hover:bg-slate-200 dark:hover:bg-slate-800" onClick={() => toggleExpandedUsers(role.id)}>
                                <div className="flex items-center gap-2 text-sm font-semibold text-slate-700 dark:text-slate-300">
                                    <UsersIcon className="w-4 h-4" />
                                    <span>Assigned Staff: {assignedUsers.length}</span>
                                </div>
                                <ChevronDownIcon className={`w-4 h-4 transition-transform ${expandedUsersRole === role.id ? 'rotate-180' : ''}`} />
                            </div>
                            
                            {expandedUsersRole === role.id && (
                                <div className="mt-2 p-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg max-h-32 overflow-y-auto">
                                    {assignedUsers.length > 0 ? (
                                        <ul className="space-y-1">
                                            {assignedUsers.map(u => (
                                                <li key={u.id} className="text-xs text-slate-600 dark:text-slate-400 flex items-center gap-2">
                                                    <div className="w-5 h-5 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-[10px] font-bold">
                                                        {u.name.charAt(0)}
                                                    </div>
                                                    {u.name}
                                                </li>
                                            ))}
                                        </ul>
                                    ) : (
                                        <p className="text-xs text-slate-500 text-center py-2">No users assigned.</p>
                                    )}
                                </div>
                            )}

                            <div className="mt-3">
                                <h4 className="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Reporting Quota</h4>
                                <p className="text-sm text-slate-600 dark:text-slate-300">
                                  {role.reportingQuotaCount && role.reportingQuotaDays
                                    ? `${role.reportingQuotaCount} reports / ${role.reportingQuotaDays} days`
                                    : 'Not set'}
                                </p>
                              </div>
                            <div className="mt-3">
                                <h4 className="text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Permissions</h4>
                                <div className="flex flex-wrap gap-1 mt-2 max-h-24 overflow-y-auto pr-1">
                                    {permissions.length > 0 && permissions[0] === '*' ? (
                                        <span className="px-2 py-0.5 text-xs font-medium rounded-full bg-green-500/20 text-green-800 dark:text-green-300">All Permissions</span>
                                    ) : (
                                        permissions.map(p => <span key={p} className="px-2 py-0.5 text-xs font-medium rounded-full bg-slate-500/20 text-slate-700 dark:text-slate-300">{p}</span>)
                                    )}
                                </div>
                            </div>
                        </div>
                         <div className="mt-4 pt-4 border-t border-slate-200/60 dark:border-slate-700/60 flex justify-end gap-4">
                            <button onClick={() => handleAssign(role)} className="font-medium text-green-600 dark:text-green-400 hover:underline">Manage Assignments</button>
                            <button onClick={() => handleEdit(role)} className="font-medium text-blue-600 dark:text-blue-400 hover:underline">Edit</button>
                        </div>
                    </div>
                )})}
            </div>
            
            {isFormModalOpen && (
                <RoleFormModal 
                    role={editingRole}
                    allRoles={roles}
                    onClose={handleCloseModal}
                    onSave={onSaveRole}
                />
            )}
             {isAssignModalOpen && assigningRole && (
                <AssignRoleModal
                    isOpen={isAssignModalOpen}
                    onClose={handleCloseAssignModal}
                    onSave={onUpdateRoleAssignments}
                    role={assigningRole}
                    allUsers={users}
                    assignments={userRoleAssignments}
                />
            )}
        </div>
    );
};

export default RoleManager;
